### PR TITLE
Rudimentary NextBot Support

### PR DESCRIPTION
**Pull request by Lemon-B-Citrom**
In order to make VJ Base NPCs attack NextBots, I have done a very rudimentary search-and-replace job in the codebase. Effectively wherever there was an `ent:IsNPC()` check, I have made it into a `(ent:IsNPC() or ent:IsNextBot())` check. 

This seems to have worked on a very simple level, but the amount of replacements probably far exceeds what is necessary to achieve this functionality. I have removed changes in files where I'm reasonably sure there would be no benefit to the replacement, but there are still a lot of files changed.

Please let me know if there are other changes in this PR where the replacements can safely be removed.

### CODE REVIEW

**Comment by IvanVladimir04** [comment]
For VJ SNPCs to target nextbots there needs to be more than just an "or" check, otherwise it would unleash a hell of bugs.

**Comment by DrVrej** [comment]
Sorry but this is very wrong to do, it was cause massive amounts of errors. After `IsNPC()` checks, I will be running any function from the NPC library and none of them exist in the Nextbot library, this would be instant error! Also attempting to bypass "VJ-NPC only" checks is not a good thing as anything after that will be using things that ONLY VJ NPCs have, thus will cause errors for anything else, including non-VJ NPCs.
For reference: https://wiki.facepunch.com/gmod/NPC

**Comment by Lemon-B-Citrom** [comment]
The places in which I have replaced IsNPC() checks do not-- so far as I have seen-- incur further VJ-base specific NPC checks and I have not run into an Lua errors while playing around with regular NPC combat. I have admittedly only tested this with the Half-Life Resurgence NPC pack. 

Is there a specific NPC you're seeing errors with?

**Comment by DrVrej** [comment]
I am not sure how you aren't getting spammed with errors from that, most of the functions I call after NPC check don't exist in nextbots, it should be creating an error for calling undefined functions. There is also another issue, all the thousands of addons created on this base have at least dozen `IsNPC` calls within them, unless we can magically update thousands of addons, this will become a issue, because the base will detect a nextbot, but those specific NPCs have no response to it, My suggestion to you is that if you are making a Nextbot and want it to support all other NPC & Nextbot bases, I highly recommend using DRGBase or Ivan04's base. Soon those 2 bases, including VJ Base are also going to be highly compatible with each other using a new system called CNS. This is currently WIP, but you can get basic information here: https://gist.github.com/DrVrej/af83c753c64270c1cc0c7864eca51b48

**Comment by Lemon-B-Citrom** [comment]
That sounds like a preferable solution to this hack, I'll look into it. Thanks for the advice.

**Pull request closed without merging**
